// Khai báo name màn hình
export const routesName = {
  LOGIN_SCREEN: "LOGIN_SCREEN",
  SIGNUP_SCREEN: "SIGNUP_SCREEN",
  BOTTOM_BAR: "BOTTOM_BAR",
  HOME_SCREEN: "HOME_SCREEN",
  FAVORITES_SCREEN: "FAVORITES_SCREEN",
  SEARCH_SCREEN: "SEARCH_SCREEN",
  PROFILE_SCREEN: "PROFILE_SCREEN",
  CREATE_SCREEN: "CREATE_SCREEN",
  BOOK_DETAIL_SCREEN: "BOOK_DETAIL_SCREEN",
  EDIT_PROFILE_SCREEN: "EDIT_PROFILE_SCREEN",
  CHANGE_PASSWORD_SCREEN: "CHANGE_PASSWORD_SCREEN",

};
